pull_request_rules:
  - name: Automatically merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - status-success=ci
    actions:
      merge:
        method: merge
